### ISSUE TITLE
Support Complex and Complex BLAS

### ISSUE THREAD

**Issue by mratsim** [mratsim/Arraymancer#129]
Nim has complex numbers in the [complex module](https://nim-lang.org/docs/complex.html).

Arraymancer should allow the same operations on `Complex` as on `SomeReal`.

BLAS is defined for complex as well and CUDA supports them.

Beyond the  well known use cases in science and engineering, supporting complex will allow the use of Fast Fourier Transform directly on Arraymancer's Tensors. This will probably be needed to implement efficient Grouped Convolution https://github.com/mratsim/Arraymancer/issues/128 without `im2col`shenanigans.

**Comment by mratsim** [comment]
Pending https://github.com/nim-lang/Nim/pull/4666

**Comment by chimez** [comment]
nimblas [https://github.com/unicredit/nimblas/pull/5](url) supports complex BLAS now, I think it's time to support complex.

**Comment by mratsim** [comment]
Merged #357 and https://github.com/mratsim/Arraymancer/commit/d03994b85c8ee69f584889a7fd7f6bc7f594f0ab
