### ISSUE TITLE
TileDB: massive dense/sparse ndarray data management by intel and MIT

### ISSUE THREAD

**Issue by skunkiferous** [mratsim/Arraymancer#138]
Hi. I did not know how to contact you more directly than on the Nim forum; I hope this is OK with you. I found something which might interest you (if you heaven't seen it yet); I might even use it myself (if I learn how to "wrap" C APIs in Nim...)

http://www.tiledb.io/

**Comment by mratsim** [comment]
No I wasn't aware, thank you.

It seems like an interesting mix between [xarray](http://xarray.pydata.org/en/stable/) with 2D matrices or 3D array being able to hold attributes and [bcolz](https://bcolz.readthedocs.io/en/latest/intro.html) / [zarr](https://github.com/alimanfoo/zarr) for the chunked/tiled compression.

For me I think this is higher-level than Arraymancer, it could use Arraymancer as a backend for computations/storage (Arraymancer can store arbitrary types, value types/stack ojects) can leverage OpenMP even if they are not numbers):
![image](https://user-images.githubusercontent.com/22738317/32244145-ee01ed62-be77-11e7-8fc0-c377eb7bf95e.png)

**Comment by skunkiferous** [comment]
Hi. I only looked superficially at Arraymancer, as I don't have need for
"scientific computing" *atm* (maybe later). I didn't realize it included
some storage functions, so I thought tileDB would be "complementary" to
your work. Anyway, I check out most new "fancy" DBs I hear of, and I want
to use "voxels", so an "array DB" seems almost perfect to store them. The
only issue I see against tileDB atm is, that if you separate dense and
sparse attributes into separate arrays, to get better storage usage, you
loose "atomicity" on updates.

On Tue, Oct 31, 2017 at 8:15 PM, Mamy Ratsimbazafy <notifications@github.com

**Comment by mratsim** [comment]
Actually I was just speaking of "in-memory/RAM storage".

**Comment by mratsim** [comment]
I'm keeping the discussion open but closing this as it's out-of-scope for Arraymancer (until I have my own cluster in my basement that is ;) ).

If someone wants to use Arraymancer as a backend for distributed computing, I would be very happy to help by introducing primitives. I'll probably explore MPI at one point but it's at the bottom of my priorities.
