### ISSUE TITLE
Implement image loader (PNG, JPG ...)

### ISSUE THREAD

**Issue by mratsim** [mratsim/Arraymancer#15]
This will probably be separated in a different package later.

Options include:
- stbimage [C]: https://github.com/nothings/stb/blob/master/stb_image.h
and [Nim]:
   - https://github.com/define-private-public/stb_image-Nim
   - https://github.com/acolley/nim-stb-image/blob/master/stbimage.nim
   - https://github.com/msiglreith/nim-stb_image
   - https://github.com/yglukhov/nimx/blob/master/nimx/load_image_impl.nim
   - https://github.com/ftsf/ld38-smalltrek/tree/master/src
- Porting PyTorch accimage [C+Python]: https://github.com/pytorch/accimage
- OpenCV [Nim]: https://github.com/dom96/nim-opencv
- Porting Pillow-SIMD [C+Python]: https://github.com/uploadcare/pillow-simd
- FreeImage [C]: http://freeimage.sourceforge.net/ (check license)
- DevIL [C++]: https://github.com/DentonW/DevIL
- Vapoursynth Image Reader [C+Python]: https://github.com/chikuzen/vsimagereader

Considerations:
- Can work on ARM
- Fast (AVX2 for x86-64 and Neon for ARM)
- Easy to integrate and maintain

Open question:
- For data augmentation like rotation/shearing, would it be better to use the library functions (tying it deeply with Arraymancer) or implement them directly on Arraymancer tensors (ensuring compatibility with all backends, and potentially using GPU acceleration)

Forum topic: https://forum.nim-lang.org/t/3056

**Comment by mratsim** [comment]
Def-pri-pub stb_image package (which is published on nimble) cannot be used at the moment due to critical issue https://github.com/define-private-public/stb_image-Nim/issues/3

**Comment by edubart** [comment]
This is already achievable through https://github.com/edubart/arraymancer-vision

**Comment by mratsim** [comment]
Closing, arraymancer-vision works well.

For reference, a few libraries I came across that might help for preprocessing or can serve as inspiration:

- [SIMD](https://github.com/ermig1979/Simd), pure assembler algorithms for AVX, AVX2, AVX512, SSE2 and ARM neon processor.
- [libvips](https://github.com/jcupitt/libvips) and [benchmarks](https://github.com/jcupitt/libvips/wiki/Speed-and-memory-use) - Note, LGPL license so we probably cannot use it as a git submodule. It can load parts of images in parallel and works on images that doesn't fit in RAM !

For inspiration:
- Python: Scikit-image/ndimage and mahotas
- Rust: [imageflow](https://github.com/imazen/imageflow). Readme has a section about how to learn  image processing and write an image library with [notes](https://github.com/imazen/Graphics-vNext/blob/master/aware.md).
- From the same guy, a list of [imaging libraries](https://github.com/nathanaeljones/imaging-wiki) he considered to write a fast, concurrent, scalable imaging library for servers

**Comment by mratsim** [comment]
2 others interesting libraries
  - [Lycon](https://github.com/ethereon/lycon), tuned for deep learning image loading
  - [Boost (Adobe) GIL](https://www.boost.org/doc/libs/1_43_0/libs/gil/doc/index.html)
