### ISSUE TITLE
unable to load

### ISSUE THREAD

**Issue by uqtredd1** [mratsim/Arraymancer#16]
Hello,

This package is exactly what I have been looking for but unfortunately I have been unable to load it. I've tried installing using the nimble package manager, with apparent success:

![image](https://user-images.githubusercontent.com/16814152/28495810-db340464-6f9d-11e7-94ab-1aa5b4b0431e.png)

And tried setting up a simple test:

![image](https://user-images.githubusercontent.com/16814152/28495817-3537dfa8-6f9e-11e7-94a1-4fdd39d61424.png)

However the compilation fails with:

![image](https://user-images.githubusercontent.com/16814152/28495830-6c961c94-6f9e-11e7-9a09-1706999b7bcf.png)

I am able to open other nimble installed packages so the problem appears specific to arraymancer. Am I missing something?

Thanks,

Tom

**Comment by mratsim** [comment]
Thanks for the report Tom.

Apparently using src in the ddirectory structure is non-trivial with nimble as the "src" will disappear.

See nimble code https://github.com/nim-lang/nimble/blob/ebf4eace3929464dba59ea21e0f9f584760fa2cf/nimble.nimble
```Nim

import ospaths
template thisModuleFile: string = instantiationInfo(fullPaths = true).filename

when fileExists(thisModuleFile.parentDir / "src/nimblepkg/common.nim"):
  # In the git repository the Nimble sources are in a ``src`` directory.
  import src/nimblepkg/common
else:
  # When the package is installed, the ``src`` directory disappears.
  import nimblepkg/common
```

I will fix that over the weekend.

**Comment by mratsim** [comment]
Sorry for the delay, it should work now with v0.1.2
