### ISSUE TITLE
Investigate slowness and memory usage compared to Python

### ISSUE THREAD

**Issue by mratsim** [mratsim/Arraymancer#190]
Reported by @narimiran on IRC

```Nim
import math
import arraymancer

const
  dz = 0.01
  z = 100
  spaceSteps = int(z / dz)
  timeSteps = 50000
  dt = 0.12 / timeSteps
  alpha = 2.0
  startingTemp = 30.0
  oscillations = 20.0

var
  Ts = startingTemp * ones[float](timeSteps, spaceSteps)


for j in 0 ..< timeSteps:
  Ts[j, 0] = startingTemp - oscillations * sin(2.0 * PI * j.float / timeSteps)

proc f(T: Tensor[float]): Tensor[float] =
  let d2T_dz2 = (T[_, 0..^3] - 2.0 * T[_, 1..^2] + T[_, 2..^1]) / dz^2
  return alpha * d2T_dz2

proc eulerSolve(Ts: var Tensor[float]) =
  for t in 0 ..< timeSteps-1:
    Ts[t+1, 1..^2] = Ts[t, 1..^2] + dt * f(Ts[t, _])
    Ts[t+1, ^1] = Ts[t+1, ^2]

Ts.eulerSolve()
```

![2018-03-03_22-18-27](https://user-images.githubusercontent.com/22738317/36939437-596b0a92-1f31-11e8-80e5-512351ac8e14.png)

**Comment by mratsim** [comment]
![2018-03-03_22-36-42](https://user-images.githubusercontent.com/22738317/36939582-6aaa90be-1f33-11e8-817d-6cd5e9f208c8.png)

**Comment by mratsim** [comment]
Nim is spending 21 seconds on this, there is a big issue on assignments:

```Nim
import math
import arraymancer

const
  dz = 0.01
  z = 100
  spaceSteps = int(z / dz)
  timeSteps = 50000
  dt = 0.12 / timeSteps
  alpha = 2.0
  startingTemp = 30.0
  oscillations = 20.0

var
  Ts = startingTemp * ones[float](timeSteps, spaceSteps)


for j in 0 ..< timeSteps:
  Ts[j, 0] = startingTemp - oscillations * sin(2.0 * PI * j.float / timeSteps)

proc f(T: Tensor[float]): Tensor[float] =
  let d2T_dz2 = (T[_, 0..^3] - 2.0 * T[_, 1..^2] + T[_, 2..^1]) / dz^2
  return alpha * d2T_dz2

proc eulerSolve(Ts: var Tensor[float]) =
  for t in 0 ..< timeSteps-1:
    # Ts[t+1, 1..^2] = Ts[t, 1..^2] + dt * f(Ts[t, _])
    # Ts[t+1, ^1] = Ts[t+1, ^2]
    discard

Ts.eulerSolve()
```

**Comment by mratsim** [comment]
There might be an allocator bug because it's not even the loop that is slow:
This takes a whooping 17seconds half of it allocating memory
```Nim
import math
import arraymancer

const
  dz = 0.01
  z = 100
  spaceSteps = int(z / dz)
  timeSteps = 50000
  dt = 0.12 / timeSteps
  alpha = 2.0
  startingTemp = 30.0
  oscillations = 20.0

var
  Ts = startingTemp * ones[float](timeSteps, spaceSteps)
```

![2018-03-03_23-13-16](https://user-images.githubusercontent.com/22738317/36939843-767b9dde-1f38-11e8-8b1e-d01eb5e3a390.png)

**Comment by mratsim** [comment]
Raised upstream: https://github.com/nim-lang/Nim/issues/7295

**Comment by narimiran** [comment]
@mratsim thank you for raising this and immediately investigating!!

**Comment by narimiran** [comment]
For a comparison, here is a version without Arraymancer, using Nim's arrays.

Notice `timeSteps = 10000` - I cannot use 50000 with arrays, it raises an error during compilation.

```nim

import math

const
  dz = 0.01
  z = 100
  spaceSteps = int(z / dz)
  timeSteps = 10000
  dt = 0.12 / timeSteps
  alpha = 2.0
  startingTemp = 30.0
  oscillations = 20.0

var Ts: array[timeSteps, array[spaceSteps, float]]

for t in 0 ..< timeSteps:
  Ts[t][0] = startingTemp - oscillations * sin(2.0 * PI * t.float / timeSteps) 
  for s in 1 ..< spaceSteps:
    Ts[t][s] = startingTemp


proc f(T: array[spaceSteps, float]): array[spaceSteps-2, float] =
  for i in 0 .. spaceSteps-3:
    result[i] = alpha * (T[i] - 2.0 * T[i+1] + T[i+2]) / dz^2


proc eulerSolve(Ts: var array[timeSteps, array[spaceSteps, float]]) =
  for t in 0 ..< timeSteps-1:
    let
      k = f(Ts[t])
    for i in 1 .. spaceSteps-2:
      Ts[t+1][i] = Ts[t][i] + dt * k[i-1]
    Ts[t+1][spaceSteps-1] = Ts[t+1][spaceSteps-2] 

Ts.eulerSolve()


echo Ts[1000][11]
echo Ts[2000][37]
echo Ts[4000][72]
```

On my computer, this runs in 0.8 sec (Arraymancer needs 2.6 sec)

**Comment by narimiran** [comment]
Python version:

```python

import numpy as np


dz = 0.01
z = 100
space_steps = int(z / dz)

time_steps = 50000
ts = np.linspace(0, 0.12, time_steps)
dt = 0.12 / time_steps
alpha = 2
starting_temp = 30
oscillations = 20

Ts = starting_temp * np.ones((time_steps, space_steps), dtype=np.float64)
Ts[:, 0] = starting_temp - oscillations * np.sin(2 * np.pi * ts / 12)


def f(T):
    d2T_dz2 = (T[:-2] - 2 * T[1:-1] + T[2:]) / dz**2
    return alpha * d2T_dz2


def euler_solve(Ts):
    for t in range(time_steps-1):
        Ts[t+1, 1:-1] = Ts[t, 1:-1] + dt * f(Ts[t])
        Ts[t+1, -1] = Ts[t+1, -2]
    return Ts


euler = euler_solve(Ts)
```

**Comment by narimiran** [comment]
> On my computer, this runs in 0.8 sec (Arraymancer needs 2.6 sec)

With the updated Arraymancer, the timings for a problem with 10000 time steps are as follows:

    nim+Arraymancer | 1.3 sec
    nim with arrays | 0.7 sec
    python+numpy    | 1.3 sec

**Comment by mratsim** [comment]
A couple updates on this:

- #193 has been merged, previously functions/computations may have been done twice if they were used as template inputs
- #164 I thought I could optimize items iteration further by implementing the TRIOT paper mentioned in the issue, (un?)fortunately the current iteration scheme is 20% faster than macros generated nested for loops

# Next steps:
There shouldn't be any reason why Arraymancer has the same speed as Python here (there is no external libraries like BLAS involved I think).
I don't think there is a way to get as fast as arrays purely on the stack though.

So:
1. I'll investigate the remaining overhead and squash it (slicing? assignments with unnecessary copies?).

**Comment by mratsim** [comment]
If you change this line:

```Nim
var
  Ts = startingTemp * ones[float](timeSteps, spaceSteps)
```

to this
```Nim
  var
    Ts = newTensorWith[float]([timeSteps, spaceSteps], startingTemp)
```

It cuts the time from 22 to 10 seconds on my machine.

**Comment by mratsim** [comment]
So after this wild day of investigation, here are my findings:

1. When benchmarking, if Python is linked to MKL it might  be surprisingly fast. I was hunting a perf difference that was due to multi-threading.

2. Slicing is actually cheap because there is no memory copied

3. The biggest performance improvement (~30%} is by avoiding temporary tensors, which you can do with the `apply3_inline` and `map3_inline` templates as showed [here](https://github.com/mratsim/Arraymancer/blob/a59a982e8a424326a2899d4e33eb0f9ff4b9674b/benchmarks/euler_tensor_optim.nim). This brings single-threaded Arraymancer within striking distance to MKL multi-threaded Numpy. (I can't compete with stack arrays yet though).

4. Unfortunately, EulerSolve at the moment is not compatible with OpenMP, computations are slowed quite hard. This is similar to what happened here: https://github.com/mratsim/Arraymancer/issues/134 and the corresponding fix: https://github.com/mratsim/Arraymancer/pull/139

The next step would be to implement a loopFusion macro with this syntax as mentionned in https://github.com/mratsim/Arraymancer/issues/145:
```Nim
proc f(T: Tensor[float]): Tensor[float] =
  loopFusion:
    a_dz2 * (T[_, 0..^3] - 2.0 * T[_, 1..^2] + T[_, 2..^1])
```

The current apply_inline templates are a bit unwieldly and do not scale beyond 3.

**Comment by Clyybber** [comment]
Should be fixed with https://github.com/nim-lang/Nim/commit/88cf6573e04bd7ee8762aa336460b9748f0d4644 but couldn't test it yet

**Comment by mratsim** [comment]
Yes on my machine single-threaded Arraymancer is as fast as multi-threaded Numpy (via OpenMP and Intel MKL) on the Euler benchmark (~6s both), so fixed for me. It is even 2.7x faster than "normal" NumPy (~16s).

The "optimized" code without any temporary allocation is even faster as it completes in 3.7s.
