### ISSUE TITLE
Superfluous `_` in slicing is hard to find (broken ex02)

### ISSUE THREAD

**Issue by bluenote10** [mratsim/Arraymancer#197]
I tried running `ex02_handwritten_digits_recognition.nim` but I got an error during accuracy testing:

```
Epoch #0 done. Testing accuracy
ex02_handwritten_digits_recognition.nim(124) ex02_handwritten_digits_recognition
p_accessors_macros_read.nim(36) slicer
p_checks.nim(67)         check_steps
Error: unhandled exception: Your slice start: 0, and stop: -1, or your step: 1, are not correct. If your step is positive
                start must be inferior to stop and inversely if your step is negative
                start must be superior to stop. [IndexError]
```

I think I have an idea what is going wrong, but it took quite some time to find the issue: I guess the problem is simply that the shape of `y_test` is one dimensional, i.e., the `_` in the expression `y_test[i ..< i+1000, _]` is probably wrong. I will provide a small PR to fix that...

Would it make sense to add another sanity check which would produce a clear error message when there is such a superfluous index?

**Comment by mratsim** [comment]
Yes you can add a new check, thanks!
