### ISSUE TITLE
linear regression example / docs

### ISSUE THREAD

**Issue by brentp** [mratsim/Arraymancer#208]
I'd like to use the linear algebra stuff in Arraymancer to do linear regression. In python/numpy, I can do this as, e.g.:

```Python
np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
```

I didn't see a matrix inversion proc in the docs or via git grep. Is this outside the scope of `Arraymancer`, or am I missing something, or other? thanks!

**Comment by mratsim** [comment]
Not at all, it's just not there because I added the deep learning stuff first.

I really need to add matrix inversion and other stuff like eigenvalues.

**Comment by mratsim** [comment]
I've started adding the numpy [lstsq](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.lstsq.html) on a branch:  https://github.com/mratsim/Arraymancer/tree/linear-regression

In the mean time you can use the neural network approach like what is done for Lua Torch using the new MSELoss (mean squared error):

 - [Lua Torch Linear Regression](https://github.com/torch/demos/blob/master/linear-regression/example-linear-regression.lua)
 - Arraymancer [example 3](
https://github.com/mratsim/Arraymancer/blob/master/examples/ex03_simple_two_layers.nim) with MSELoss that can be adapted.

**Comment by mratsim** [comment]
Done, you can use the new least_squares_solver, similar to there: https://github.com/mratsim/Arraymancer/blob/master/tests/linear_algebra/test_linear_algebra.nim

**Comment by brentp** [comment]
awesome!! thank you. I'll give it a try this week.
