### ISSUE TITLE
Recurrence

### ISSUE THREAD

**Issue by clive-g-brown** [mratsim/Arraymancer#253]
How would you  implement recurrence / LSTM ?

**Comment by clive-g-brown** [comment]
I guess I mean an example usage (of say Gru)

**Comment by mratsim** [comment]
Hello @clive-g-brown, for now only the low-level primitives for GRU Cell is implemented, you can check its use there: https://github.com/mratsim/Arraymancer/blob/master/tests/nn_primitives/test_nnp_gru.nim but it's not really user friendly.

I did not have the time to implement a full GRU (a combination of GRUCell for each timestep) nor the high-API which should end up similar to PyTorch.
