### ISSUE TITLE
nimble build fails on nim devel with: Error: undeclared identifier: 'stmt'

### ISSUE THREAD

**Issue by timotheecour** [mratsim/Arraymancer#258]
nim --version
Nim Compiler Version 0.18.1 [MacOSX: amd64]
Compiled at 2018-07-20
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: f92d61b1f4e193bd17e1f76722d26f1f0605ad17
active boot switches: -d:release

nimble build
   Warning: Package 'arraymancer' has an incorrect structure. It should contain a single directory hierarchy for source files, named 'arraymancer', but file 'maxpool2D.nim' is in a directory named 'nn/layers' instead. This will be an error in the future.
      Hint: If 'nn/layers' contains source files for building 'arraymancer', rename it to 'arraymancer'. Otherwise, prevent its installation by adding `skipDirs = @["nn/layers"]` to the .nimble file.
  Verifying dependencies for arraymancer@0.4.0
      Info: Dependency on nimblas@>= 0.1.3 already satisfied
  Verifying dependencies for nimblas@0.2.1
      Info: Dependency on nimlapack@>= 0.1.1 already satisfied
  Verifying dependencies for nimlapack@0.1.1
      Info: Dependency on nimcuda@>= 0.1.4 already satisfied
  Verifying dependencies for nimcuda@0.1.5
 Installing nimcl@>= 0.1.2
Downloading https://github.com/unicredit/nimcl using git
       Tip: 22 messages have been suppressed, use --verbose to show them.
     Error: Could not read package info file in /tmp/nimble_14025/githubcom_unicreditnimcl_0.1.2/nimcl.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...     /private/tmp/nimble_14025/githubcom_unicreditnimcl_0.1.2/nimcl.nimble(11, 37) Error: undeclared identifier: 'stmt'.

**Comment by bckpkol** [comment]
Why is that closed, I still have this issue.

**Comment by timotheecour** [comment]
I don't have issue above but I have this new issue instead: https://github.com/mratsim/Arraymancer/issues/309
are you having #258 or #309 ?

(I'm using latest version)

**Comment by mratsim** [comment]
@bckpkol This was fixed in nimcl: https://github.com/unicredit/nimcl/pull/2
