### ISSUE TITLE
How to install and use with OpenCL?

### ISSUE THREAD

**Issue by kazimuth** [mratsim/Arraymancer#280]
I'm slightly perplexed about how to use OpenCL with ArrayMancer. I'm on OS X 10.12.6, nim 0.18.

Doing `nimble install arraymancer@#head` doesn't give me e.g. the `opencl` function to create opencl tensors.

Building from source with `-d:opencl` gives me an error about the `clblast` library not being installed. Once I install that, I can build with `nim c -d:opencl src/arraymancer.nim`, but I can't install that.

Is there something I'm doing wrong? Could this be documented?

**Comment by mratsim** [comment]
You don't "install" Arraymancer. It does not build a DLL, at least at the moment. It's just a collection of source files.

Once you did `nimble install arraymancer@#head` and installed clblast (it should be done automatically), you can write the following code:

```Nim
# myfile.nim
import arraymancer

let a =  [[1.0, 2, 3, 4],
            [5.0, 6, 7, 8]].toTensor
let a_cl = a.opencl
```

Compile with `nim c -d:opencl myfile.nim` and it will use OpenCL.
