### ISSUE TITLE
Broken Link on Docs

### ISSUE THREAD

**Issue by juancarlospaco** [mratsim/Arraymancer#344]
**Broken Link on Docs:**
https://mratsim.github.io/Arraymancer/nnp.nnp_conv2D_cudnn.html

**From:**
https://mratsim.github.io/Arraymancer/index.html
- Technical Reference --> Neuralnet Primitives

:slightly_smiling_face:

**Comment by mratsim** [comment]
Fixed in one of the 0.6.0 doc updates:
- https://github.com/mratsim/Arraymancer/commit/7e7713e74f035e8c45fe166024afe9d12a222a17
- https://github.com/mratsim/Arraymancer/commit/30b294e6ade0bf0affeba4225e2b741286a99c0b

IIRC it was a case sensitiveness issue
