### ISSUE TITLE
Too slow when copying data back and forth from pyObject

### ISSUE THREAD

**Issue by zaferarican** [mratsim/Arraymancer#353]
I want to process numpy array data on nim by using arraymancer. 
I use nimpy as a bridge between nim and python. I have a repo where I have an example to perform in-place integral image computation and I wanted to move first data to an arraymancer tensor process and put it back to a python object. The code is available at  [nimpy_numpy_examples#arraymancer](
https://github.com/zaferarican/nimpy_numpy_examples/tree/arraymancer).

When I do like that, the process is very slow. Probably, it is due to data transfer between pyObject and tensor. Is there a better way to do that? 

Is it possible to use pyRawBuffer as data field of the tensor?

**Comment by Vindaar** [comment]
Just had a super short look, but here: https://github.com/zaferarican/nimpy_numpy_examples/blob/arraymancer/nimpy_numpy_examples/nimpy_integral_arraymancer.nim#L25-L31 
you don't have to create a 2D sequence to convert that to a tensor. Plus, you should allocate a sequence of the correct size from the start. Tensors store the data in a 1D data structure anyways and the shape is only in the meta data. :)
So something like
```nim
var seq_xy = newSeq[cint](rows * columns) # <-- already allocate the size of the sequence!
for i in 0 ..< rows * columns:
    seq_xy[i] = aBuf[i]  # assuming you define an accessor for single index
result = newTensor[cint](rows, columns)
result.data = seq_xy # use `data=` to assign the data directly 
# alternatively
# result = seq_xy.toTensor.reshape(rows, columns)
```
where I'm using the implicit `result` variable that Nim provides. For the `data=` see here:
https://mratsim.github.io/Arraymancer/tensor.data_structure.html

Sort of related and maybe helpful to you too, see Arraymancers numpy file interface here: 
https://github.com/mratsim/Arraymancer/blob/master/src/io/io_npy.nim
to see how raw access to the tensor internals is handled there.

**Comment by zaferarican** [comment]
Thanks @Vindaar for your suggestion. 
Unfortunately, convertion of data as you showed did not help either. It did not improve the speed. 

With direct access to pyBuffer, the integral image implementation in Nim is faster than OpenCV implementation. It is great but when I try to move it to arraymancer, it becomes 25x slower. I do not think it is related to arraymancer but to moving data to/from arraymancer.

Is there a way for example such that
```nim
var aBuf: RawPyBuffer 
o.getBuffer(aBuf, PyBUF_WRITABLE or PyBUF_ND)
the_tensor.data = aBuf 
```

**Comment by Vindaar** [comment]
Ok, that's unfortunate. I thought allocating the whole seq would have a big impact already. It makes sense of course that avoiding allocation is fastest.
I'm not sure how supported and safe it is, but I guess you could cast the `RawPyBuffer` just to `ptr UncheckedArray[cint]`, get the offset data pointer using `dataArray`
https://mratsim.github.io/Arraymancer/tensor.data_structure.html#dataArray%2CTensor%5BT%5D
and set that pointer to the `RawPyBuffer` pointer?

**Comment by zaferarican** [comment]
Hi @Vindaar, 
Thanks. Using get_data_ptr actually helped. I used copyMem to copy all data at once from RawPyBuffer ptr to tensor ptr. I committed the code at [nimpy_numpy_examples#arraymancer](
https://github.com/zaferarican/nimpy_numpy_examples/tree/arraymancer).

Although it is slower than the direct access example, it is around 10x-15x faster than element by element copy. I think the convenience in using arraymancer is worth the overhead.

**Comment by mratsim** [comment]
Thanks @Vindaar for the support.

In the future the new backend Laser will allow no-copy operations on any pointer + metadata pair without having to copy into a seq:

See - https://github.com/mratsim/Arraymancer/issues/262#issuecomment-432985491

and the future low-level implementation: https://github.com/numforge/laser/blob/0cb91fc2e9cb0d10f23c2fbb64aca54c160a2cc0/laser/tensor/datatypes.nim#L18-L30

```Nim
const LASER_MAXRANK*{.intdefine.} = 6
  # On x86-64, a cache line can contain 8 int64. Hence for best performance
  # MAXRANK should be at most 8 on x86_64 machines
  # Unless, you want to index using int32 which limits dimensions
  # tensor dimensions to 2 billions elements.

type DynamicStackArray*[T] = object
    ## Custom stack allocated array that behaves like seq.
    ## We must avoid seq creation when modifying tensor shapes, strides or slicing in a tight loop.
    ## Seq creation are also not possible within an OpenMP loop.
    data*: array[LASER_MAXRANK, T]
    len*: int

  Metadata* = DynamicStackArray[int]

  Tensor*[T] = object                    # Total stack: 128 bytes = 2 cache-lines
    shape*: Metadata                     # 56 bytes
    strides*: Metadata                   # 56 bytes
    offset*: int                         # 8 bytes
    storage*: CpuStorage[T]              # 8 bytes

  CpuStorage*{.shallow.}[T] = ref object # Total heap: 25 bytes = 1 cache-line
    when supportsCopyMem(T):
      raw_data*: ptr UncheckedArray[T]   # 8 bytes
      memalloc*: pointer                 # 8 bytes
      memowner*: bool                    # 1 byte
    else: # Tensors of strings, other ref types or non-trivial destructors
      raw_data*: seq[T]                  # 8 bytes (16 for seq v2 backed by destructors?)
```
