### ISSUE TITLE
docs are not searchable

### ISSUE THREAD

**Issue by brentp** [mratsim/Arraymancer#354]
for someone coming into arraymancer, it's hard to use the docs.
the drop-downs run past the bottom of my screen and it's not clear which to choose for a given operation.
For example, I want the elementwise min of 2 tensors of shape `[$n]` the best I could come up with is:

```Nim
concat(a, b, axis=0).reshape(a.shape[0], 2).min(axis=1).squeeze(1)
```
is there a better way?

I suppose I could use forEach in `laser`, but I thought there could be a simple way within arraymancer.

**Comment by mratsim** [comment]
Unfortunately I'm very bad at frontend work and I did what I could with Nim facilities. Hopefully there will be a Nim documentation project or a maintained sphinx integration.

I'm unsure what you mean by elementwise, in your code you are doing axiswise iteration.

`forEach` in laser wouldn't work for an axis iteration.

In Arraymancer you can use `zipAxis` to avoid intermediate allocation of `concat`

```Nim
iterator zipAxis*[T, U](a: Tensor[T], b: Tensor[U], axis: int): tuple[a: Tensor[T], b: Tensor[U]] {.inline.}=
  ## Inline iterator over 2 tensors over an axis.
  ##
  ## Returns:
  ##   - 2 slices along the given axis at each iteration.
  ##
  ## Note: The slice dimension is not collapsed by default.
  ## You can use ``squeeze`` to collapse it.
```

but for your use case I would use the following instead:

```Nim
import arraymancer

let a = randomTensor([3, 5], 20)
let b = randomTensor([3, 5], 20)

echo a
# Tensor[system.int] of shape [3, 5] of type "int" on backend "Cpu"
# |14     0       11      20      8|
# |14     11      2       18      14|
# |1      15      10      6       2|

echo b
# Tensor[system.int] of shape [3, 5] of type "int" on backend "Cpu"
# |12     10      2       3       9|
# |2      15      0       6       20|
# |8      3       6       11      17|

# If elementwise
let m = min:
  map2_inline(a, b):
    min(x, y)

echo m
# 0

# If axis-wise
let n1 = min(a, axis = 0)
let n2 = min(b, axis = 0)

let n = map2_inline(n1, n2):
  min(x, y)

echo n
# Tensor[system.int] of shape [1, 5] of type "int" on backend "Cpu"
# |1      0       0       3       2|
```

**Comment by brentp** [comment]
I hear you on the front-end stuff. I have the same problem.
Looks like map2_inline is what I need. Thanks for the answer and the software.
