### ISSUE TITLE
implement QR factorization

### ISSUE THREAD

**Issue by brentp** [mratsim/Arraymancer#376]
I'm not familiar with lapack or any linalg really, but I started this and got as far as:
```Nim
import
  ../../tensor/tensor, ../../linear_algebra/linear_algebra, 
  nimlapack

proc geqrf(m: ptr cint; n: ptr cint; a: ptr cfloat; lda: ptr cint;
           tau: ptr cfloat; work: ptr cfloat; lwork: ptr cint; info: ptr cint) {.inline.}=
  # http://www.netlib.org/lapack/explore-html/d8/ddc/group__real_g_ecomputational_ga7cb54fa1727bf0166523036f4948bc56.html
  sgeqrf(m, n, a, lda, tau, work, lwork, info)

proc qr*[T : SomeFloat](x: Tensor[T]): tuple[q : Tensor[T], r : Tensor[T]] = 
  result.q = x.copy()
  var tau = zeros[float32](min(result.q.shape))
  var work = newSeq[float32](1)
  var
    lwork:cint = -1
    info:cint = 0 
    m:cint = result.q.shape[0]
    n:cint = result.q.shape[1]
    lda:cint = max(1, result.q.shape[0])
  # with lwork set to -1, calculate lwork
  geqrf(m.addr, n.addr, result.q[0].addr, lda.addr, tau[0].addr, work[0].addr, lwork.addr, info.addr)
  if info != 0:
    quit "bad"
  
  lwork = max(1, result.q.shape[1], work[0].abs)
  work = newSeq[float32](lwork)
  
  geqrf(m.addr, n.addr, result.q[0].addr, lda.addr, tau[0].addr, work[0].addr, lwork.addr, info.addr)
  if info != 0:
    quit "bad"
  # now what?

```

**Comment by mratsim** [comment]
Yeah writing and debugging Lapack was really painful, I can have a look in about 2 weeks.

All my experience with LAPACK comes from implementing symeig for SVD/eigenvecs decomposition (https://github.com/mratsim/Arraymancer/blob/master/src/linear_algebra/decomposition.nim) and least square solver (https://github.com/mratsim/Arraymancer/blob/master/src/linear_algebra/least_squares.nim).

My best source of example was [Intel's examples](https://software.intel.com/sites/products/documentation/doclib/mkl_sa/11/mkl_lapack_examples/intelmat.htm) but it does not seem there is one for ?geqrf

**Comment by mratsim** [comment]
So this one takes the cake.

geqrf doesn't return Q but the result of elementary Householder Reflectors:
- See description of: https://software.intel.com/en-us/mkl-developer-reference-c-geqrf
- Explanation of Householder Reflections: https://www.quantstart.com/articles/QR-Decomposition-with-Python-and-NumPy

Several follow-up are available on those reflections depending on what we want:
- solving a linear system, we want `ormqr`: https://stackoverflow.com/questions/21970510/solving-a-linear-system-with-lapacks-dgeqrf
- for the Q matrix, we want `orgqr`: https://github.com/numpy/numpy/blob/v1.15.1/numpy/linalg/linalg.py#L928
