### ISSUE TITLE
Got wrong tensor when reshape after permute or transpose.

### ISSUE THREAD

**Issue by kvinwang** [mratsim/Arraymancer#386]
```nim
  var x = [[0, 1], [2, 3]].toTensor
  x = x.permute(1, 0).reshape(2, 2)
  echo x
  echo x[0, 1]
```

Expected:
```
Tensor[system.int] of shape [2, 2] of type "int" on backend "Cpu"
|0      2|
|1      3|

2

```
Actual:
```
Tensor[system.int] of shape [2, 2] of type "int" on backend "Cpu"
|0      1|
|2      3|

1
```

**Comment by mratsim** [comment]
Thanks. This happens because I have an optimization to reshape tensors without copy if they are contiguous.

However this can only work if both the input and output of reshape have the same contiguity (row-major/col-major). The code was mistakenly always using a row-major output.

Fixed by #395
