### ISSUE TITLE
Complex converter issue

### ISSUE THREAD

**Issue by mratsim** [mratsim/Arraymancer#394]
See forum post:

```nim
import arraymancer, fft, utils
import complex

let s: Tensor[float] = hamming[float](1024)
var data = fft(s).map(abs)
write_npy(data, "hanning_fft.npy")
```

```
/root/.nimble/pkgs/arraymancer-0.5.2/io/io_npy.nim(172, 22) Error: ambiguous call; both system.$(x: uint64) [declared in /root/.choosenim/toolchains/nim-#devel/lib/system/strmantle.nim(288, 6)] and complex.$(z: Complex) [declared in /root/.choosenim/toolchains/nim-#devel/lib/pure/complex.nim(344, 6)] match for: (byte)
```

The converter should probably be removed as they might trigger other hard-to-debug bugs. Also they might significantly impact compile-time and compilation memory usage #359 #362

**Comment by xflywind** [comment]
Are converters in arraymancer private? and shouldn't be open?
```Nim
import arraymancer, complex

let a: int = 1
echo a * 3.2
```
The number is converted to complex implictly.When I import arraymancer
and complex module at the same time.

**Comment by mratsim** [comment]
I think having public converter in a library are a mistake as it makes errors due to implicit conversion hard to debug while explicit conversion is hard to track down. Furthermore as mentioned in the forum, it pollutes the namespace without offering a way around that (contrary to proc which can be prefixed with the module name).

At the very least converters should be restricted to literals for libraries.

Furthermore, I get 33% memory saving and 20% compilation speed on a test_operator_blas at first glance. This will be important for Arraymancer use with hot-code reloading / jupyter kernel

Applications built on-top of Arraymancer should implement their own converter instead.
