### ISSUE TITLE
Tensor higher order functions syntax: aggregate, map, fmap, fold, reduce, apply ...

### ISSUE THREAD

**Issue by mratsim** [mratsim/Arraymancer#41]
There are several aggregation/higher order functions that have various names depending on the language/library.

It would be nice to be (in no particular order):
  1. Descriptive and unambiguous

  2. Consistent within Nim ecosystem:
       - [sequtils](https://nim-lang.org/docs/sequtils.html)
             - `map` to apply a function to all elements creating a new object |-> Arraymancer `fmap`
             - `apply` to apply a function *in-place* to all elements. |-> Arraymancer `apply` pending https://github.com/mratsim/Arraymancer/pull/40
       - [Nimdata](https://github.com/bluenote10/NimData)
             - `map` to apply a function to all elements creating a new object |-> Arraymancer `fmap`
             - `reduce` to aggregate on all elements of an object |-> Arraymancer `agg`
             - `fold` to aggregate on all elements of an object |-> Arraymancer `agg_inplace`
       - [neo](https://github.com/unicredit/neo)
             - `map` to apply a function to all elements creating a new object |-> Arraymancer `fmap`

  3. Familiar, if possible, with users coming from other languages, non-Nim libraries, for (non-exhaustive) example:
        - Pandas
             - `map` to apply a function to all elements of a series (column/row) |-> No series concept in Arraymancer (use `fmap`)
             - `applymap` to apply a function to all elements of a dataframe |-> Arraymancer `fmap`
             - `apply` to apply a function along an axis |-> Arraymancer `agg` with axis argument
             - `agg`/`aggregate` to aggregate over an axis (semantics are different from `apply` on pandas GroupBy objects which Arraymancer doesn't have) |-> Arraymancer `agg`
        - Functional languages and Map/Reduce jargon. See [Wikipedia fold comparison](https://en.wikipedia.org/wiki/Fold_%28higher-order_function%29#Folds_in_various_languages)
             - Haskell defines `map` for Lists and `fmap` (and `liftM`) for Monads (generic containers)
             - Haskell's `foldr`/`foldl` takes an initial argument/accumulator value, `foldl1`/`foldr1` doesn't
             - F# has `fold`/`foldBack` (init val) and `reduce`/`reduceBack` (no init val)
             - Scala has `foldLeft`/`foldRight` (init val) and `reduceLeft`/`reduceRight` (no init val).

Proposition:
  - Abandon `fmap` for `map` , same as `nimData`, `neo` and `sequtils`. Anyway `fmap` in Haskell had interesting [controversies](https://stackoverflow.com/questions/7463500/why-do-we-have-map-fmap-and-liftm)
  - `fmap_inplace` in PR https://github.com/mratsim/Arraymancer/pull/40 will be called `apply` to be consistent with `sequtils` cc @edubart 
  - `agg` which is a name with poor discoverability/familiarity will be changed to `reduce` similar to `NimData`, F# and Scala
  - `agg_inplace` (with init value) will be changed to `fold`

cc @bluenote10 and @andreaferretti. If you have any input to make Nim scientific ecosystem better or at least consistent feel free.

**Comment by bluenote10** [comment]
Sounds very good to me.

One thing to note: To me the main difference between `reduce` and `fold` is the implied type relation. If you look at the signatures in Scala

```scala
// given e.g. List[A]
def reduceLeft[B >: A](op: (B, A) ⇒ B): B // note the B >: A type relation
def foldLeft[B](z: B)(op: (B, A) ⇒ B): B
```

you can see that `reduce` cannot break out of the type hierarchy of `A`. For instance you can only reduce a `List[String]` to a result of `String` or supertypes of `String` like `Any`. With `fold` however, `B` can take arbitrary types, e.g. you can sum the string lengths to an `Int` result. Specifying an initial value for `B` is just a necessity to leave the type hierarchy.

You might want to consider having left/right versions if you feel a need for non-associative reduces/folds.

**Comment by edubart** [comment]
Sound good to me, I find `reduce` much more clear than `agg`, same regarding `fmap` => `map` and `fmap_inplace` => `apply`

**Comment by mratsim** [comment]
Thanks for your inputs. Closed by https://github.com/mratsim/Arraymancer/pull/45.
