### ISSUE TITLE
update Arraymancer version to 0.6.0 in arraymancer.nimble

### ISSUE THREAD

**Issue by HugoGranstrom** [mratsim/Arraymancer#414]
The latest release is `v0.6.0` but the version in `arraymancer.nimble` is `0.5.2` so Nimble won't install the correct version.

**Comment by yay** [comment]
Running `nimble run project` still yields the following error:

<img width="742" alt="Screen Shot 2020-05-03 at 9 00 02 PM" src="https://user-images.githubusercontent.com/1799756/80924478-1290d280-8d81-11ea-95d1-5a344a7f01e6.png">

I have the following in `project.nimble`:

<img width="257" alt="Screen Shot 2020-05-03 at 9 00 13 PM" src="https://user-images.githubusercontent.com/1799756/80924481-1c1a3a80-8d81-11ea-8982-487e0011faea.png">

**Comment by yay** [comment]
Also, the artifacts for v0.6.0 here https://github.com/mratsim/Arraymancer/releases still have v0.5.2 in the `arraymancer.nimble` file.
