### ISSUE TITLE
Fref_tracking not initialised in CudeStorage?

### ISSUE THREAD

**Issue by cmacmackin** [mratsim/Arraymancer#418]
Perhaps I'm missing something here, but looking through the code of `tensor/backend/cuda.nim` it looks like [newCudaStorage](https://github.com/mratsim/Arraymancer/blob/4c114fed3af9298070a1127d26f2cc263692296f/src/tensor/backend/cuda.nim#L37) isn't setting the pointer in `Fref_tracking` to point at `Fdata`. On the other hand [newClStorage](https://github.com/mratsim/Arraymancer/blob/4c114fed3af9298070a1127d26f2cc263692296f/src/tensor/backend/opencl_backend.nim#L49) does do that.

**Comment by mratsim** [comment]
Indeed, good catch
