### ISSUE TITLE
Arraymancer is bugged with gc:arc

### ISSUE THREAD

**Issue by Clonkk** [mratsim/Arraymancer#423]
Arraymancer seems to be bugged with --gc:arc.

I encouter blocking code / segfault on Tensor operation.
The following code allows to reproduce with --gc:arc:
```
import arraymancer

proc doubleMe(data : Tensor[float]): Tensor[float]=
  result = data*2

proc squareMe(data : Tensor[float]): Tensor[float]=
  result = data*.data

let A : seq[float] = @[0.11, 0.12, 0.13, 0.14]
echo A.type
echo A
var B : Tensor[float] = A.toTensor
echo B
# Blocking
var C = doubleMe(B)
echo C
#Segfault
var D = squareMe(C)
echo D
```

It works fine with any other gc. 

I installed arraymancer with `nimble install arraymancer@#head`

Nim version is latest devel : 
Nim Compiler Version 1.1.1 [Linux: amd64]
Compiled at 2020-03-05
Copyright (c) 2006-2019 by Andreas Rumpf

**Comment by mratsim** [comment]
This might change (for the better or maybe for worse) with #420 as non-string tensors would not be backed by sequences anymore but raw memory buffers.

**Comment by Clonkk** [comment]
With https://github.com/mratsim/Arraymancer/pull/477 merged, should this be closed ?

**Comment by Vindaar** [comment]
Yes, I agree. To be certain I just verified that your example now works fine.

Closing this (with the caveat that self assignment of certain operations under ARC is still broken):
- our test case: https://github.com/mratsim/Arraymancer/blob/master/tests/tensor/test_init.nim#L177-L183
- upstream issue: https://github.com/nim-lang/Nim/issues/16185
