### ISSUE TITLE
Documentation issue about the NumPy runtime asymptotics in the YOLO section

### ISSUE THREAD

**Issue by kartynnik** [mratsim/Arraymancer#428]
The [YOLO section](https://mratsim.github.io/Arraymancer/uth.speed.html) has a phrase "So you suddenly get a o(n^4) algorithm."
Actually the algorithm there is O(N), being several linear algorithms chained together.

**Comment by Vindaar** [comment]
@kartynnik Thanks for the report, but that has already been fixed. The docs have just not been updated yet.

**Comment by kartynnik** [comment]
Got it, thanks. Technically, every linear algorithm is <img src="https://render.githubusercontent.com/render/math?math=o(n^4)"> (and <img src="https://render.githubusercontent.com/render/math?math=O(n^4)"> which is slightly different and was probably intended there) because it's an upper bound (and thus Arraymancer uses an <img src="https://render.githubusercontent.com/render/math?math=o(n^200)"> algorithm... :smile:). But it creates the wrong impression for those who are not intimately familiar with asymptotics notations.

Feel free to close this issue when the updated documentation is rolled out.

**Comment by mratsim** [comment]
Fixed in the new docs
