### ISSUE TITLE
Span slicing inside dynamic type procs fails to compile

### ISSUE THREAD

**Issue by edubart** [mratsim/Arraymancer#43]
Minor test case:

```Nim
import arraymancer

proc boo[T](): T =
  var a = zeros([2,2], int)
  echo a[1,_]

discard boo[int]()
```

When compiling the following error is shown:
```
test.nim(4, 12) Error: undeclared identifier: '_'
```

Removing dynamic type `[T]` from the proc the code works fine.

**Comment by mratsim** [comment]
I've reproduced it and reported it to Nim upstream.

It seems like for generic procs, there is an identifier resolution happening before the macros kick-in and replace "_".

I may have a workaround by exporting a dummy "_" but I don't want to pollute namespace with that symbol. And it's used in tuple pattern-matching as well and maybe by other libs.

**Comment by mratsim** [comment]
You can workaround that issue by using `mixin _` from module macros in the procs that uses "_"

**Comment by edubart** [comment]
This workaround does not work with more complex silicing, like `x[_, _, ^1..0|-1]`

**Comment by mratsim** [comment]
Not sure which identifier poses the issue here, with seq I can "solve" it by adding everything as mixin :/

```Nim
proc foo4[T](): CustomSeq[T] =
  result.data.newSeq(10)
  # weird fancy corner case that feels special and wants special treatment
  mixin _,`|-`
  # why?
  echo result[_, _, ^1..0|-1]
```

Case is closed upstream, but I really think generics have an issue as detailed by Krux
