### ISSUE TITLE
Allow independent imports

### ISSUE THREAD

**Issue by mratsim** [mratsim/Arraymancer#439]
See https://github.com/Vindaar/ggplotnim/pull/63#issuecomment-613089036

We should allow `import arraymancer/tensors` at least so that Nim doesn't try to typecheck/semcheck all the ml, linear algebra or deep learning modules.

**Comment by Vindaar** [comment]
This has since been implemented. It was part of https://github.com/mratsim/Arraymancer/pull/464.
