### ISSUE TITLE
Ellipsis slicing syntax

### ISSUE THREAD

**Issue by edubart** [mratsim/Arraymancer#44]
Just like numpy, allow to use the ellipsis `...` when slicing in `x[..., 0]`, expanding `...` to spans `_` matching the tensor rank in the slice operation. For example if x rank is 3:

`x[..., 0]` => `x[_, _, 0]`
`x[0, ...]` => `x[0, _, _]`
`x[..., 0, 0, 0]` => `x[0, 0, 0]`
`x[0, 0, 0, ...]` => `x[0, 0, 0]`

Optionally, although maybe less used:

`x[0, ..., 0]` => `x[0, _, 0]`
`x[0, 0, ..., 0]` => `x[0, 0, 0]`

**Comment by edubart** [comment]
This is a useful feature to make functions flexible to work with both single tensor and a batch of tensors using the same code

**Comment by mratsim** [comment]
Done in https://github.com/mratsim/Arraymancer/commit/9000595477de3c52a7b8dee672f4c785d373a40d and https://github.com/mratsim/Arraymancer/commit/13542e92a950a495f46f68f3a6bfc3ab784e5ded
