### ISSUE TITLE
x86 routine called on ARM

### ISSUE THREAD

**Issue by sdwfrost** [mratsim/Arraymancer#454]
Dear @mratsim 

Thanks for all your work (and proposed work) on getting Arraymancer to work on ARM. Here's another issue that seems to be related to switches between architectures.

```
@scpuinfo_x86.nim.c:193:2: error: impossible constraint in 'asm'
  asm("      cpuid\n"
  ^~~
```

This comes up e.g. when trying to compile one of the files in @Vindaar ggplotnim [https://github.com/Vindaar/ggplotnim](https://github.com/Vindaar/ggplotnim)

**Comment by mratsim** [comment]
I think there is no blocker left now.
