### ISSUE TITLE
Euclidean distances

### ISSUE THREAD

**Issue by jyapayne** [mratsim/Arraymancer#469]
Hi, I'm a bit new to the ML scene and I am trying to convert [this python script](https://github.com/rmodi6/gesture-recognition/blob/master/server.py) to Nim.

I've figured out most of it except there is a function called `euclidean_distances` ([from here](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.euclidean_distances.html)) from sklearn that I'm unsure how to translate using Arraymancer. I see that there is a proc in `kmeans.nim` called `euclidean_distance` (without the `s`). It seems to be mostly what I want, except it returns a single number instead of a Tensor. 

Is there a proc somewhere that performs the euclidean distances similar to the Python library? Just asking before I go on the journey of implementing it myself. Or maybe you can provide a tip on how to implement it simply with the defined proc :) Thank you!

**Comment by Vindaar** [comment]
Without having looked deeply into this, at a glance it seems to me as if the euclidean distance function in arraymancer can only calculate the distance between two vectors. The scikit-learn function generalizes that to compatible matrices, namely input can be:
- a: NxM matrix
- b: MxN matrix

and the result is a vector containing the the distances between each pair of a, b. Using normal index notation for matrices (that is first index is the row and second the column), this means it calculates:
```
c = (a_i1 · b_1i, a_i2 · b_2i, a_i3 · b_3i)ᵀ
```
in case of two 3x3 matrices.

So essentially to calculate what you want you need to call the existing `euclidean_distance` function in arraymancer for each "(row, column) pair" or essentially walk over all rows of a and bᵀ (transpose of b).

```nim
# let a, b be two compatible matrices
for (a_row, b_col) in zipAxis(a, b.T, 0):
  echo euclidean_distance(a_row, b_row)
```
putting together those results into a new tensor, should do what scikit-learn does.

Hope this helps somewhat.

I think the reason arraymancer does not support the operation in a more generalized way is that `dot` is also not generalized to matrices. It can only work with vectors at the moment, if I'm not mistaken.

**Comment by jyapayne** [comment]
@Vindaar Thank you for the detailed response! This is exactly what I needed. I will try your suggestion.

**Comment by jyapayne** [comment]
Hmm, I can't seem to get this to work properly. If `X` is a matrix like `[[0, 1], [1, 1]]` and `Y` is a matrix like `[[0, 0], [0, 0], [0, 0]]`, in python I get this:

```python
>>> import numpy as np
>>> from sklearn.metrics.pairwise import euclidean_distances
>>> Y = np.array([[0, 0], [0, 0], [0,0]])
>>> X = np.array([[0, 1], [1, 1]])
>>> euclidean_distances(X, Y)
array([[1.        , 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356]])
```

But this code results in an error for Nim. Here's my complete code I came up with:

```nim
import math
import sequtils
import arraymancer
import arraymancer / ml / clustering / kmeans

proc euclideanDistance[T: SomeFloat](u: Tensor[T], v: Tensor[T], squared: bool = false): T {.noInit.} =
  let u_v = (u -. v).reshape(u.shape[1])
  result = dot(u_v, u_v)
  if not squared:
    result = sqrt(result)

proc euclideanDistances[T: SomeFloat](X: Tensor[T], Y: Tensor[T], squared: bool = false): Tensor[T] {.noInit.} =
  var res = newSeq[T](Y.shape[1])

  var i = 0
  for aRow, bRow in zipAxis(X, Y.transpose, 0):
    res[i] = euclideanDistance(aRow, bRow, squared)
    i += 1
  
  # This will have to be changed for the correct dimensions
  result = res.toTensor

proc main() =
  let X = @[0.0, 1, 1, 1].toTensor.reshape(2, 2)
  let Y = @[0.0, 0.0, 0, 0, 0, 0].toTensor.reshape(3, 2)

  echo euclideanDistances(X, Y)

main()
```

I get this error:

```
/Users/joey/Projects/arraymancer/examples/test.nim(28) test
/Users/joey/Projects/arraymancer/examples/test.nim(26) main
/Users/joey/Projects/arraymancer/examples/test.nim(17) euclideanDistances
/Users/joey/Projects/arraymancer/examples/test.nim(7) euclideanDistance
/Users/joey/Projects/arraymancer/src/arraymancer/tensor/operators_broadcasted.nim(34) -.
/Users/joey/Projects/arraymancer/src/arraymancer/tensor/shapeshifting.nim(171) broadcast2
/Users/joey/Projects/arraymancer/src/arraymancer/tensor/private/p_shapeshifting.nim(106) broadcast2Impl
Error: unhandled exception: Broadcasting error: non-singleton dimensions must be the same in both tensors. Tensors' shapes were: [1, 2] and [1, 3] [ValueError]
Error: execution of an external program failed: '/Users/joey/Projects/arraymancer/examples/test '
```

I know it has to do with the tensor shapes not having the correct shape (from the error message). But I'm not sure what to do with it or how to manipulate the code to get a valid euclidean distance.

**Comment by Vindaar** [comment]
Sorry, I wasn't thinking straight with the usage of the `forAxis` iterator. That iterator skips most (row, column) pairs of course (it yields N elements for NxN matrices, whereas of course we need NxN elements).

 Give me a few minutes.

**Comment by Vindaar** [comment]
Aside from not thinking properly when using the `forAxis` iterator, I really should have read the scikit-learn documentation. I made a wrong assumption about how they generalize the calculation.

Instead of taking (NxM, MxN) matrices it already expects the user to hand (NxM, NxM) matrices. That is in scikit-learn lingo:
- x: (n_samples_1, n_features)
- y: (n_samples_2, n_features)

which for the use case in scikit-learn makes sense I suppose. I approached it with a too math focused point of view. Sorry for the confusion!

With that in mind, we can write a custom iterator, which yields the correct row pairs (and only rows!). Essentially we have to yield each row in x once for each row in y. In code:

```nim
import arraymancer

let Y = [[0,0], [0,0], [0,0]].toTensor.asType(float).reshape(3, 2)
let X = [[0,1], [1,1]].toTensor.asType(float)
echo X
echo Y

iterator zipRowPairs[T](x, y: Tensor[T]): ((int, Tensor[T]), (int, Tensor[T])) =
  ## Given input tensors of shapes:
  ## x: (n_samples_1, n_features)
  ## y: (n_samples_2, n_features)
  ## yields n_features² pairs of (n_features_1_i, n_features_2_j)
  doAssert x.rank == 2
  doAssert y.rank == 2
  doAssert x.shape[1] == y.shape[1]
  for xRows in 0 ..< x.shape[0]:
    for yRows in 0 ..< y.shape[0]:
      yield ((xRows, x[xRows, _]), (yRows, y[yRows, _]))


var res = zeros[float](2, 3)
for xTup, yTup in zipRowPairs(X, Y):
  let (i, xRow) = xTup
  let (j, yRow) = yTup
  echo xRow,  "    ", yRow
  res[i, j] = euclidean_distance(xRow, yRow)
echo res
```
The return value of the iterator isn't exactly pretty, but for clarity I wanted to make it this verbose. Feel free to just return the indices and perform the slicing in the `euclidean_distance` call.

Note, I just exported the `euclidean_distance` proc of the kmeans file.

**Comment by jyapayne** [comment]
@Vindaar wow! Thank you for putting in the effort to explain and the very useful code example! I learned a lot about arraymancer from just reading through it :)

I've managed to use your example to get the correct output and now I'm on my way to translating the rest of that python code. Thank you so much for your help!

This is the resulting code in case it's usefult to anyone:

```nim
import math
import sequtils
import arraymancer

iterator zipRowPairs[T](x, y: Tensor[T]): ((int, Tensor[T]), (int, Tensor[T])) =
  ## Given input tensors of shapes:
  ## x: (n_samples_1, n_features)
  ## y: (n_samples_2, n_features)
  ## yields n_features² pairs of (n_features_1_i, n_features_2_j)
  doAssert x.rank == 2
  doAssert y.rank == 2
  doAssert x.shape[1] == y.shape[1]
  for xRows in 0 ..< x.shape[0]:
    for yRows in 0 ..< y.shape[0]:
      yield ((xRows, x[xRows, _]), (yRows, y[yRows, _]))

proc euclideanDistance[T: SomeFloat](u: Tensor[T], v: Tensor[T], squared: bool = false): T {.noInit.} =
  ## Calculates the euclidean distance
  ## Inputs:
  ##  - u: a tensor of shape (nb samples, nb features)
  ##  - v: a tensor of shape (nb samples, nb features)
  ##  - squared: whether or not to square the result
  ##
  ## sqrt( (u - v) dot (u - v) )
  ## which can be reformulated
  ## sqrt((u dot u) - 2 * (u dot v) + (v dot v))
  ##
  ## Returns:
  ##  - A tensor of shape (nb samples)
  let u_v = (u -. v).reshape(u.shape[1])
  result = dot(u_v, u_v)
  if not squared:
    result = sqrt(result)

proc euclideanDistances[T: SomeFloat](X: Tensor[T], Y: Tensor[T], squared: bool = false): Tensor[T] {.noInit.} =
  ## Calculates the euclidean distances
  ## Inputs:
  ##  - u: a tensor of shape (nb samples 1, nb features)
  ##  - v: a tensor of shape (nb samples 2, nb features)
  ##  - squared: whether or not to square the result
  ##
  ## Returns:
  ##  - A tensor of shape (X.shape[0], Y.shape[0])
  result = zeros[T](X.shape[0], Y.shape[0])

  for xTup, yTup in zipRowPairs(X, Y):
    let (i, xRow) = xTup
    let (j, yRow) = yTup
    result[i, j] = euclideanDistance(xRow, yRow, squared)

proc main() =
  let X = [[0,1], [1,1]].toTensor.asType(float)
  let Y = [[0, 0], [0, 0], [0, 0]].toTensor.asType(float)

  echo euclideanDistances(X, Y)

main()
```

**Comment by Vindaar** [comment]
@jyapayne You're welcome! I'm always happy to help other people. Especially in our tiny community here. :)

Even if that sometimes means I have to live with the fact that I sometimes write ambiguous / confusing / or possibly even wrong information (like in my first post) and bear my brain's feeling of shame, haha.

**Comment by jyapayne** [comment]
No worries at all. Mistakes are part of coding :) I've made many embarrassing comments and solutions too! I'm just grateful you helped! Thanks again!
