### ISSUE TITLE
Is there a built in way to pad a tensor?

### ISSUE THREAD

**Issue by xioren** [mratsim/Arraymancer#470]
Looking for something similar to numpy.pad(). I have searched the docs and the issues to no avail. Thanks.

**Comment by mratsim** [comment]
There are no builtin way currently, you have 2 workarounds:

1. Either reate tensors that you `concat` on the required edges
2. Or create a larger (N+1)x(N+1) zero tensor for example and `slice[1..^1, 1..^1]` your tensor in.

**Comment by xioren** [comment]
I see, thanks.
