### ISSUE TITLE
git tag needs to be bumped up after updating the nimble version in .nimble file

### ISSUE THREAD

**Issue by kaushalmodi** [mratsim/Arraymancer#473]
Right now, `nimble install arraymancer` installs v0.5.2.

[Ref][1]

cc: @Vindaar 

[1]: https://gitter.im/SciNim/community?at=5fa05113d37a1a13d680ad69

**Comment by Vindaar** [comment]
With `v0.6.1` tagged this can be closed. I confirmed `v0.6.1` is correctly installed using `nimble install arraymancer`.

**Comment by kaushalmodi** [comment]
Thanks. I confirm the fix.
