### ISSUE TITLE
Compilation error when usinf least_squares_solver

### ISSUE THREAD

**Issue by lscrd** [mratsim/Arraymancer#496]
Hi,

When using “least_squares_solver” I get a compilation error.

Here is an example:

```Nim
import arraymancer

var a = [[1.0, 2.0], [1.0, 7.0]].toTensor
var b = [2.0, 4.0].toTensor

echo leastSquaresSolver(a, b)

```
And here is the error:

```Nim
/...../.nimble/pkgs/arraymancer-0.6.2/arraymancer/linear_algebra/least_squares.nim(16, 8) template/generic instantiation of `gelsd` from here
/....../.nimble/pkgs/arraymancer-0.6.2/arraymancer/linear_algebra/helpers/least_squares_lapack.nim(75, 85) Error: type mismatch: got <int32, int literal(2)>
but expected one of: 
template `^`(x: int): BackwardsIndex
  first type mismatch at position: 2
  extra argument given

2 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them

expression: 26'i32 ^ 2
```

Looking into “arraymancer/linear_algebra/helpers/least_squares_lapack.nim” it appears that the error occurs in this line:

```Nim
lwork = max(1, 12 * m + 2 * m * smlsiz + 8 * m * nlvl + m * nrhs + (smlsiz + 1) ^ 2)
```

and especially with `(smlsiz + 1) ^ 2`.

It looks like the operator `^` for integers is not available at this point.

I have been able to solve the issue either by replacing `(smlsiz + 1) ^ 2` with `(smlsiz + 1) * (smlsiz + 1)` or by adding somewhere ```from math import `^` ```.

Of course, we can import math before importing arraymancer which solves the problem.

**Comment by Vindaar** [comment]
As mentioned in the PR, the problem is that `^` is at least nowadays part of `math`, which was not imported in the least squares lapack helper file.
