### ISSUE TITLE
Random forest regression

### ISSUE THREAD

**Issue by C-NERD** [mratsim/Arraymancer#501]
Sorry to bring this up here but, i want to use random forest regression for a project and i have searched arraymancer's source code and documentation and i was unable to find an implementation. If there is an implementation, I would really appreciate it if you could point me to the part of the source code where it is implemented.

**Comment by Vindaar** [comment]
There is no such thing at the moment in arraymancer. PRs are of course welcome!

But there is the following package on nimble:
https://github.com/Michedev/DecisionTreeNim
which might just provide what you want.

**Comment by C-NERD** [comment]
Ok thanks I'll check out the decision tree package and I'll also try to implement linear, polynomial and random forest regression using arraymancer.
