### ISSUE TITLE
shakespeare_generator doesn't compile on Nim 1.4.8 / Arraymancer 0.7.1

### ISSUE THREAD

**Issue by Anuken** [mratsim/Arraymancer#514]
Compilation of [this example](https://github.com/mratsim/Arraymancer/blob/master/examples/ex06_shakespeare_generator.nim) fails with an [error](https://github.com/mratsim/Arraymancer/blob/master/examples/ex06_shakespeare_generator.nim#L59): 

`(59, 6) Error: 'strToTensor' can have side effects`

This appears to be caused by a `newTensor` call adding side effects. Making all the `func`s `proc`s in the example fails with a different error: `'optimizerAdam' can have side effects`.

[This line](https://github.com/mratsim/Arraymancer/blob/master/examples/ex06_shakespeare_generator.nim#L295) also gives me a "wrong number of arguments" / "illformed AST" error in VS Code, but I'm not sure how accurate it is with other errors blocking compilation.

This is my first time trying out the library, so I'm not sure if the examples are outdated or whether I'm doing something wrong. Are they tested in CI? If not, it might be worth ensuring that they still compile with each new release/breaking change.

```
Nim Compiler Version 1.4.8 [Linux: amd64]
arraymancer  [0.7.1]
Command: nim r -d:danger <example_file>
```

**Comment by Vindaar** [comment]
It's quite likely that there are some regressions here. The examples aren't part of the CI at the moment (but maybe they should be! Some of them are just a bit compute heavy and would have to be run as a sort of dummy).

I'll take a look at it later.

**Comment by Anuken** [comment]
> Some of them are just a bit compute heavy and would have to be run as a sort of dummy with few iterations

Right, but running something like `nim c` on every example might still be useful to identify problems like these.

**Comment by Vindaar** [comment]
If the issue still persists after updating, please reopen.

As there is currently no tag for latest master, you need to install #head. If I can fix #459 as well, I'll tag another mini release.

**Comment by Vindaar** [comment]
I've just tagged a new release `v0.7.2`.

**Comment by Anuken** [comment]
Compilation succeeds now, thanks for the quick fix!
