### ISSUE TITLE
Subdimensional indexing

### ISSUE THREAD

**Issue by edubart** [mratsim/Arraymancer#55]
Let **A** be a **C**x**M**x**N** tensor, to access its subdimensional matrix **B** of size **M**x**N** at index **c** in the **C** axis currently we have to do,

```Nim
B  = A[c, _, _].reshape([M,N])
```

and if we want to access without copy,

```Nim
B = A.unsafeView(c, _, _).unsafeReshape([M,N])
```

both ways is not ease of use, instead a more conventional way would be,

```Nim
B = A.at(c)
```

and without copy,

```Nim
B = A.unsafeAt(c)
```

**Comment by mratsim** [comment]
Fixed by: https://github.com/mratsim/Arraymancer/commit/f06c4d25998409622108e1b402111cbc9e8b87b9

**Comment by edubart** [comment]
This is not complete,  currently I have to do `B = A.at(c, _, _)` instead of  `B = A.at(c)` 
also it should squeeze everything, we want to squeeze only the dimensions passed in the parameters.

**Comment by mratsim** [comment]
I think this should be done with the ellipsis syntax no? https://github.com/mratsim/Arraymancer/issues/44

What if we want A[_, c, _, _], why would A.at(c) choose the first dim and not one of the other?

Or maybe is the function the same as [index_select](http://pytorch.org/docs/master/torch.html#torch.index_select)?

**Comment by edubart** [comment]
I want to use this specifically in codes that I don't know the number of dimensions beforehand, what I meant by at, is this in numpy:

```Python
In [2]: import numpy as np

In [3]: a = np.random.rand(2,2)

In [4]: a
Out[4]: 
array([[ 0.64126719,  0.34654449],
       [ 0.15411641,  0.3445235 ]])

In [5]: a[0]
Out[5]: array([ 0.64126719,  0.34654449])

In [6]: a[0][0]
Out[6]: 0.64126718794123549
````

In this example `a[0]` returns a 1d vector, and  `a[0][0]` a float, `at` would do the same similar. This gives this conventional interface to access subdimensional tensors.

This could be achieved with ellipsis syntax, however we don't have it yet, I thought doing this can be easier before the full ellipsis implementation. But yeah implementing the ellipsis would accomplish this already.

**Comment by mratsim** [comment]
Done via ellipsis in https://github.com/mratsim/Arraymancer/commit/9000595477de3c52a7b8dee672f4c785d373a40d and https://github.com/mratsim/Arraymancer/commit/13542e92a950a495f46f68f3a6bfc3ab784e5ded
