### ISSUE TITLE
Device workload split feature

### ISSUE THREAD

**Issue by AndreasKaratzas** [mratsim/Arraymancer#576]
Question: Is it possible to split a neural network between different accelerators (e.g. CPU, GPU)? A solution that "kinda" works is also welcome.

**Comment by Vindaar** [comment]
At least currently there's no real way to do this. I'm not sure if you could hack something to that effect, but it seems unlikely to me.

**Comment by AndreasKaratzas** [comment]
It would be really interesting to see in the future such a feature. It would enable researchers that work on heterogeneous architectures to rapidly design their prototypes.
