### ISSUE TITLE
ShallowCopy  problem using Nim v2 RCx

### ISSUE THREAD

**Issue by general-rishkin** [mratsim/Arraymancer#585]
Arraymancer does not work with Nim v2 RCx.
I tried running the example on the GitHub page but got the following error:

`/home/grishkin/.nimble/pkgs/arraymancer-0.7.12/arraymancer/laser/tensor/initialization.nim(232, 5) Error: undeclared identifier: 'shallowCopy'`

Are there plans to fix this by using 'move' as suggested by the release notes (I think)?
What timeline are we looking at?

**Comment by ringabout** [comment]
@Vindaar I suppose It was fixed by https://github.com/mratsim/Arraymancer/pull/562

**Comment by Vindaar** [comment]
Ah, thanks for the ping. If for some reason this can still be triggered after all, feel free to reopen @general-rishkin.
