### ISSUE TITLE
Error: cannot open file: ./math

### ISSUE THREAD

**Issue by greenersharp** [mratsim/Arraymancer#669]
Hi,

I just installed arraymancer to test it for the first time.

I ran:

`apt-get install libopenblas-dev`
`apt-get install liblapack-dev`
`nimble install arraymancer`

Then I tried a simple test:
```
import arraymancer

let d = [[1, 2, 3], [4, 5, 6]].toTensor()

echo d
```

Then I ran it with:
nim c --mm:orc simpletest.nim

I then get the following output and error:
```
.......................................................................
/home/redacted/.nimble/pkgs/nimblas-0.2.2/nimblas/private/common.nim(50, 7) Hint: Using BLAS library with name: libblas.so(||.3|.2|.1|.0) [User]
......................................................................................................................
/home/redacted/.nimble/pkgs/arraymancer-0.7.12/arraymancer/tensor/operators_broadcasted.nim(18, 9) Error: cannot open file: ./math

```

Any ideas what I'm doing wrong ?

Thank you

**Comment by Vindaar** [comment]
The issue was because you're still on version 0.7.12. I assume you noticed it and updated to the latest tag?

**Comment by greenersharp** [comment]
Yes exactly.

I just had to uninstall arraymancer and then reinstall it.
