### ISSUE TITLE
Random tensor with float32

### ISSUE THREAD

**Issue by edubart** [mratsim/Arraymancer#68]
`randomTensor([2,2], 1.0'f32)` returns a random float64 tensor instead of float32

**Comment by mratsim** [comment]
Yes I saw that and mentionned it on IRC in the past week (or the bug tracker but I coudn't find it again). It's actually not a bug (not on Arraymancer side at least).

The signature should only works with float (float64)
```Nim
proc randomTensor*(shape: openarray[int], max: float): Tensor[float] =
  randomTensorCpu(result, shape, max)
```

But Nim silently converts the argument to float64, and returns float64 ...

**Comment by mratsim** [comment]
Raised upstream: https://github.com/nim-lang/Nim/issues/6432
