### ISSUE TITLE
newSeqUninitialized regression

### ISSUE THREAD

**Issue by mratsim** [mratsim/Arraymancer#70]
The following builds failed on devel only but not on stable.
This is probably following the usage of the new [newSeqUnitialized](https://github.com/nim-lang/Nim/pull/6402)

https://travis-ci.org/mratsim/Arraymancer/jobs/279307094
```
Traceback (most recent call last)
accessors_slicer.nim(467) test_accessors
system.nim(3547)         *=
system.nim(2727)         sysFatal
    Unhandled exception: over- or underflow
  [FAILED] indexing + in-place operator
```
https://travis-ci.org/mratsim/Arraymancer/jobs/279307258
```
  [OK] Iterators
    test_accessors.nim(93, 13): Check failed: a == [[0, 0, 0], [0, 200, 0], [0, 0, 0]].toTensor
    a was Tensor of shape 3x3 of type "int" on backend "Cpu"
|4	8	16|
|9	740	81|
|16	64	256|
  [FAILED] indexing + in-place operator
```
[Suite] Accessing and setting tensor values
  [OK] Accessing and setting a single value
  [OK] Out of bounds checking
  [OK] Iterators
    test_accessors.nim(93, 13): Check failed: a == [[0, 0, 0], [0, 200, 0], [0, 0, 0]].toTensor
    a was Tensor of shape 3x3 of type "int" on backend "Cpu"
|4	8	16|
|9	740	81|
|16	64	256|
  [FAILED] indexing + in-place operator
```

cc @edubart

**Comment by edubart** [comment]
I cannot reproduce, nim's devel branch and nim's stable works for me.
Could you reproduce at home?

**Comment by mratsim** [comment]
Found it, it's probably there:

```Nim
proc newTensor*(shape: openarray[int], T: typedesc): Tensor[T] {.noSideEffect, inline.} =
  ## Creates a new Tensor on Cpu backend
  ## Input:
  ##      - Shape of the Tensor
  ##      - Type of its elements
  ## Result:
  ##      - A Tensor of the proper shape initialized with
  ##        the default type value (0 for numeric types) on Cpu backend
  tensorCpu(shape, result)
  result.data = newSeqUninitialized[T](result.size) ### <---- Now newTensor does not start with 0
```

Was that intentional? I'd rather create a "newTensorUninitialized" proc

**Comment by edubart** [comment]
Its intentional, we have zeros() already to crete one filled with zeros.

**Comment by edubart** [comment]
You can change the name if you like then.

**Comment by mratsim** [comment]
Yes I will create a different one `newTensorUninitialized`. newTensor is supposed to work with all types including strings and objects not only numerical ones.

**Comment by mratsim** [comment]
Fixed: https://github.com/mratsim/Arraymancer/commit/ea7508c0724a7df7559b68cf8c8470d9ee0d1588
