### ISSUE TITLE
OpenMP crashes in debug mode

### ISSUE THREAD

**Issue by edubart** [mratsim/Arraymancer#78]
Curretly OpenMP only works in release mode, in debug mode there are some allocations being made, and with the current GC design allocating from OMP threads is not supported. Some seqs (for example calling is_C_Contiguous does allocate a seq) and strings are being allocated in the OMP threads, why? 

Investigate further, do we need to mark OMP functions as Gcsafe or something?

**Comment by mratsim** [comment]
I can't even compile with GCC or clang in release mode for some reason.

I think I did something while configuring nvcc and have to repair that.

**Comment by edubart** [comment]
The problem is a combination of closures + stackTrace:on + openmp, will leave this as a note here to someday fix properly. Usually happens with intensive tasks, arraymancer tests will not trigger the issue, you have to run an intensive task like a neural network model. The strack tracer seems to allocate strings for tracking down closures inside openmp threads which is wrong because the nim GC doesn't know that is inside a new thread, using pragma `{.push stackTrace:off.}` has no effect.

Workaround is to compile with --stackTrace:off when using openmp.

**Comment by mratsim** [comment]
Solved by: https://github.com/mratsim/Arraymancer/pull/90
